# Generated by Django 4.2.4 on 2023-09-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("end_year", models.CharField(max_length=100, null=True)),
                ("intensity", models.CharField(max_length=100, null=True)),
                ("sector", models.CharField(max_length=100, null=True)),
                ("topic", models.CharField(max_length=100, null=True)),
                ("insight", models.CharField(max_length=100, null=True)),
                ("url", models.CharField(max_length=100, null=True)),
                ("start_year", models.CharField(max_length=100, null=True)),
                ("impact", models.CharField(max_length=100, null=True)),
                ("added", models.CharField(max_length=100, null=True)),
                ("published", models.CharField(max_length=100, null=True)),
                ("country", models.CharField(max_length=100, null=True)),
                ("relevance", models.CharField(max_length=100, null=True)),
                ("pestle", models.CharField(max_length=100, null=True)),
                ("source", models.CharField(max_length=100, null=True)),
                ("title", models.CharField(max_length=100, null=True)),
                ("likelihood", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
